services:
  app-a:
    build:
      context: .
      dockerfile: build/a.Dockerfile
    restart: always
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      APP_NAME: 'my-app-a'
      APP_A_HOST: 'http://app-a:8080'
      APP_B_HOST: 'http://app-b:8081'
      OTEL_HOST: 'otel-collector:4317'
    depends_on:
      - app-b

  app-b:
    build:
      context: .
      dockerfile: build/b.Dockerfile
    restart: always
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
      APP_NAME: 'my-app-b'
      APP_A_HOST: 'http://app-a:8080'
      APP_B_HOST: 'http://app-b:8081'
      OTEL_HOST: 'otel-collector:4317'
    depends_on:
      - otel-collector

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./.docker/otel-config.yaml:/etc/otel-collector-config.yaml
    command: ['--config', '/etc/otel-collector-config.yaml']
    ports:
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
      - '55681:55681' # legacy (opcional)
      - '8889:8889' # metrics pipeline (Prometheus scrape)
    depends_on:
      - prometheus
      - zipkin

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - '9411:9411'

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus.yaml
    command: ['--config.file=/etc/prometheus.yaml']
    ports:
      - '9090:9090'
